CREATE TABLE NGUOIDUNG (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_ND VARCHAR(255) NOT NULL,
    EMAIL_VERIFIED_AT DATETIME NULL,
    REMEMBER_TOKEN VARCHAR(255) NULL,
    ROLE ENUM('admin', 'manager', 'student') NOT NULL DEFAULT 'student';
);

CREATE TABLE QUANLY (
    ID_QL INT AUTO_INCREMENT PRIMARY KEY,
    HO_TEN_QL VARCHAR(100) NOT NULL,
    CONTACT_QL VARCHAR(50) NOT NULL,
    ADDRESS_QL VARCHAR(200) NOT NULL,
    IMAGE_QL VARCHAR(255),
    ID_USER INT NOT NULL,
    ID_TOA INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES NGUOIDUNG(ID_USER),
    FOREIGN KEY (ID_TOA) REFERENCES TOA(ID_TOA)
);

CREATE TABLE TOA (
    ID_TOA INT NOT NULL PRIMARY KEY,
    TEN_TOA VARCHAR(100) NOT NULL
);

CREATE TABLE PHONG (
    ID_ROOM INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_NAME VARCHAR(50) NOT NULL,
    CAPACITY INT,
    OCCUPIED_SLOT INT,
    ID_TOA INT NOT NULL,
    GIOI_TINH ENUM('Nam', 'Nữ') NOT NULL DEFAULT 'Nam',
    FOREIGN KEY (ID_TOA) REFERENCES TOA(ID_TOA)
);

CREATE TABLE SINHVIEN (
    MSSV VARCHAR(20) NOT NULL PRIMARY KEY,
    HO_TEN_SV VARCHAR(100) NOT NULL,
    CONTACT_SV VARCHAR(50) NOT NULL,
    ADDRESS_SV VARCHAR(200) NOT NULL,
    GIOI_TINH ENUM('Nam', 'Nữ') NOT NULL DEFAULT 'Nam',
    -- SEMESTER_DK VARCHAR(50) NOT NULL,
    -- IMAGE_SV VARCHAR(255),
    ID_USER INT NOT NULL,
    ID_ROOM INT NOT NULL,
    FOREIGN KEY (ID_ROOM) REFERENCES PHONG(ID_ROOM),
    FOREIGN KEY (ID_USER) REFERENCES NGUOIDUNG(ID_USER)
);

CREATE TABLE VANDE (
    ID_VD INT AUTO_INCREMENT PRIMARY KEY,
    MO_TA_VD VARCHAR(255),
    MSSV VARCHAR(20) NOT NULL,
    ID_QL INT NOT NULL,
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (ID_QL) REFERENCES QUANLY(ID_QL)
);

CREATE TABLE HOADON (
    ID_HOADON INT AUTO_INCREMENT PRIMARY KEY,
    LOAI_HOADON VARCHAR(100),
    SO_TIEN DECIMAL(18,2),
    NOTE_HOADON VARCHAR(255),
    MSSV VARCHAR(20) NOT NULL,
    ID_QL INT NOT NULL,
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (ID_QL) REFERENCES QUANLY(ID_QL)
);

CREATE TABLE COSOVATCHAT (
    ID_CSVC INT AUTO_INCREMENT PRIMARY KEY,
    LOAI_CSVC VARCHAR(100) NOT NULL,
    STATUS_CSVC VARCHAR(50) NOT NULL,
    NOTE_CSVC VARCHAR(255),
    IMAGE_CSVC VARCHAR(255),
    ID_ROOM INT NOT NULL,
    FOREIGN KEY (ID_ROOM) REFERENCES PHONG(ID_ROOM)
);

CREATE TABLE DONDANGKY (
    ID_DON INT AUTO_INCREMENT PRIMARY KEY,
    HO_TEN_NDK VARCHAR(100) NOT NULL,
    MSSV_NDK VARCHAR(20) NOT NULL,
    SDT_NDK VARCHAR(20) NOT NULL,
    EMAIL_NDK VARCHAR(100) NOT NULL,
    STATUS_DON ENUM('Chưa xử lý', 'Đã chấp nhận', 'Đã từ chối') NOT NULL DEFAULT 'Chưa xử lý',
    THOI_DIEM_TAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_QL) REFERENCES QUANLY(ID_QL)
);

CREATE TABLE THONGBAO (
    ID_TB INT AUTO_INCREMENT PRIMARY KEY,
    TITLE_TB VARCHAR(255) NOT NULL,
    FILE_TB VARCHAR(255),
    ID_QL INT NULL,
    FOREIGN KEY (ID_QL) REFERENCES QUANLY(ID_QL)
);