USE infidorm;
CREATE TABLE USERS
(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ROLE INT,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASS VARCHAR(255) NOT NULL,
    EMAIL_VERIFIED_AT DATETIME NULL,
    REMEMBER_TOKEN VARCHAR(255) NULL
);

CREATE TABLE BLOCK
(
    BLOCK_ID VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE MANAGER
(
    MNG_ID VARCHAR(20) PRIMARY KEY,
    MNG_NAME VARCHAR(100) NOT NULL,
    MNG_DOB DATETIME NOT NULL,
    MNG_GD VARCHAR(10),
    MNG_PHONE VARCHAR(20),
    MNG_ADR VARCHAR(200),
    MNG_IMG VARCHAR(255),
    MNG_BLOCK VARCHAR(10),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (MNG_BLOCK) REFERENCES BLOCK(BLOCK_ID)
);

CREATE TABLE ROOM
(
    ROOM_ID VARCHAR(10) PRIMARY KEY,
    CAPACITY INT,
    OCCUPIED INT,
    BLOCK_ID VARCHAR(10) NOT NULL,
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK(BLOCK_ID)
);

CREATE TABLE STUDENT
(
    STD_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    STD_NAME VARCHAR(100) NOT NULL,
    STD_DOB DATETIME NOT NULL,
    STD_GD VARCHAR(10) NOT NULL,
    STD_PHONE VARCHAR(20) NOT NULL,
    STD_ADR VARCHAR(200) NOT NULL,
    STARTDATE DATETIME,
    ENDDATE DATETIME,
    STD_IMG VARCHAR(255),
    USER_ID INT NOT NULL,
    BLOCK_ID VARCHAR(10),
    ROOM_ID VARCHAR(10),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK(BLOCK_ID)
);

CREATE TABLE PROBLEM
(
    PR_ID INT AUTO_INCREMENT PRIMARY KEY,
    PR_TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255),
    STD_ID VARCHAR(20) NOT NULL,
    BLOCK_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (STD_ID) REFERENCES STUDENT(STD_ID),
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK(BLOCK_ID)
);

-- Khoản thu(ID, Năm, Tháng, Tòa, Phòng, Số điện, Khối nước, Khác, Note đi kèm nếu có khác)
CREATE TABLE REVENUE
(
    REV_ID INT AUTO_INCREMENT PRIMARY KEY,
    REV_YEAR INT,
    REV_MONTH INT,
    BLOCK_ID VARCHAR(10) NOT NULL,
    ROOM_ID VARCHAR(10) NOT NULL,
    ELEC INT,
    WATER INT,
    OTHER INT,
    NOTE VARCHAR(255),
    FOREIGN KEY(BLOCK_ID) REFERENCES BLOCK(BLOCK_ID),
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

-- Đơn Giá (Điện, Nước, theo từng tháng / năm cụ thể, có thể nhập tay tùy ý, do ADMIN làm, các tòa giống như nhau)
CREATE TABLE UNIT
(
    UYEAR INT,
    UMONTH INT,
    ELEC INT NOT NULL,
    WATER INT NOT NULL,
    PRIMARY KEY (UYEAR, UMONTH)
);

CREATE TABLE FACILITY
(
    FCLT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FCLT_TYPE VARCHAR(100) NOT NULL,
    FCLT_STATUS VARCHAR(50),
    FCLT_NOTE VARCHAR(255),
    FCLT_IMG VARCHAR(255),
    ROOM_ID VARCHAR(10) NOT NULL,
    BLOCK_ID VARCHAR(10) NOT NULL,
    FOREIGN KEY(BLOCK_ID) REFERENCES ROOM(BLOCK_ID),
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE REGIFORM
(
    REG_ID INT AUTO_INCREMENT PRIMARY KEY,
    REG_NAME VARCHAR(100) NOT NULL,
    REG_STD_ID VARCHAR(20) NOT NULL,
    REG_PHONE VARCHAR(20) NOT NULL,
    REG_EMAIL VARCHAR(100) NOT NULL,
    REG_STATUS VARCHAR(50)
);

CREATE TABLE NOTI
(
    NOTI_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255),
    NOTI_DATE DATETIME,
    MNG_ID VARCHAR(20),
    FOREIGN KEY (MNG_ID) REFERENCES MANAGER(MNG_ID)
);

INSERT INTO USERS (EMAIL, PASS, EMAIL_VERIFIED_AT)
VALUES
('admin@infidorm.com', '123456', NOW()),
('manager@infidorm.com', '123456', NOW()),
('s1@infidorm.com', '123456', NOW()),
('s2@infidorm.com', '123456', NOW()),
('s3@infidorm.com', '123456', NOW()),
('s4@infidorm.com', '123456', NOW()),
('s5@infidorm.com', '123456', NOW()),
('s6@infidorm.com', '123456', NOW()),
('s7@infidorm.com', '123456', NOW()),
('s8@infidorm.com', '123456', NOW());

INSERT INTO BLOCK (BLOCK_ID)
VALUES ('A'), ('B'), ('C'), ('D');

INSERT INTO MANAGER
(MNG_ID, MNG_NAME, MNG_DOB, MNG_GD, MNG_PHONE, MNG_ADR, USER_ID, MNG_BLOCK)
VALUES
('M01', 'Nguyễn Văn A', '1985-05-20', 'Nam', '0901234567', 'Hà Nội', 2, 'A');

INSERT INTO ROOM (ROOM_ID, CAPACITY, BLOCK_ID)
VALUES
('A101', 6, 'A'),
('A102', 6, 'A'),
('A201', 8, 'A'),
('A202', 8, 'A'),
('B101', 8, 'B'),
('B102', 8, 'B');

INSERT INTO STUDENT
(STD_ID, STD_NAME, STD_DOB, STD_GD, STD_PHONE, STD_ADR, USER_ID, BLOCK_ID, ROOM_ID)
VALUES
('20235001', 'Trần Thị B', '2004-03-15', 'Nữ', '0987654321', 'Nam Định', 3, 'A', 'A101'),
('20235040', 'Lê Văn C', '2003-08-10', 'Nam', '0977123456', 'Thái Bình', 4, 'A', 'A101'),
('20210001', 'Phạm Minh Tuấn', '2003-05-10', 'Nam', '0987654321', 'Hà Nội', 5, 'A', 'A101'),
('20210002', 'Lê Thị Hoa', '2003-08-15', 'Nữ', '0987654322', 'Hải Phòng', 6, 'A', 'A101'),
('20210003', 'Hoàng Văn Nam', '2003-02-20', 'Nam', '0987654323', 'Nam Định', 7, 'A', 'A102'),
('20210004', 'Nguyễn Thị Lan', '2003-11-05', 'Nữ', '0987654324', 'Thanh Hóa', 8, 'B', 'B102'),
('20210005', 'Trần Văn Đức', '2003-06-30', 'Nam', '0987654325', 'Nghệ An', 9, 'B', 'B101'),
('20210006', 'Trần Văn Đức', '2003-06-30', 'Nam', '0987654325', 'Nghệ An', 10, 'B', 'B101');

INSERT INTO REGIFORM (REG_NAME, REG_STD_ID, REG_PHONE, REG_EMAIL)
VALUES
('Vũ Thị Mai', '20220001', '0912345678', 'mai@student.hust.edu.vn'),
('Đỗ Văn Hùng', '20220002', '0912345679', 'hung@student.hust.edu.vn'),
('Bùi Thị Thu', '20220003', '0912345680', 'thu@student.hust.edu.vn');
